name: "Terraform setup and apply"
description: "Applys a terraform plan file from an artifact"
inputs:
  hello: 
    description: 'where to execute terraform'
    required: true
  terraform_directory:
    description: 'Directory that holds Terraform code'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      working-directory: ${{ inputs.terraform_directory  }}
      run: terraform fmt -check
      shell: bash

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_directory  }}
      run: terraform init
      shell: bash
 
    - name: Terraform Validate
      id: validate
      working-directory: ${{ inputs.terraform_directory  }}
      run: terraform validate -no-color
      shell: bash

    - name: Terraform Plan
      id: plan
      working-directory: ${{ inputs.terraform_directory  }}
      run: terraform plan -no-color
      shell: bash

    - name: Setup Terraform
      run: echo "Hello world ${{ inputs.hello }}"
      shell: bash


