name: 'GitHub Actions Demo'
inputs:
  hello:
    description: 'Log level'
    required: true
    default: test

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      
      - name: Hello
        run: |
          echo "Log level: ${{ github.event.inputs.logLevel }}"


