Name: Starter Workflow Demo
on:
  workflow_call:
    inputs:
      hello:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: demo workflow job
        run: echo This is a demo start workflow
