name: 'Terraform - Backed Dev'

on: [push]

jobs:
  path-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
             path1:
              - '.github/workflows/**'
             path2:
              - 'Path2/**'
  terraform:
        needs: path-files
        uses: ./.github/workflows/github_terraform.yml
        with:
          hello: "test"
          terraform_directory: "./Backend/dev"

