name: Bump version

on: 
  workflow_call:
    inputs:
      environment:
        description: "Environment"
        required: true
        type: string
      github_token:
        description: 'Github token'
        required: true
        type: string


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ inputs.github_token }}
#          tag_prefix: ${{ inputs.environment }}

      - name: Output of step
        run: echo " tag is ${{ steps.tag_version.outputs.new_tag }}" && pwd

#      - name: Create a GitHub release
#        uses: ncipollo/release-action@v1
#        with:
#          tag: ${{ steps.tag_version.outputs.new_tag }}
#          name: Release ${{ steps.tag_version.outputs.new_tag }}
#          body: ${{ steps.tag_version.outputs.changelog }}
