name: 'Terraform - Backed Dev'
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  path-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            backend_dev:
              - 'Backend/dev/**'
            backend_qc:
              - 'Backend/qc/**'
            backend_prod:
              - 'Backend/prod/**'
            frontend_dev:
              - 'Frontend/dev/**'
            frontend_qc:
              - 'Frontend/qc/**'
            frontend_prod:
              - 'Frontend/prod/**'



  terraform:
    needs: path-files
    uses: ./.github/workflows/github_terraform.yml
    with:
      terraform_directory: "./Backend/dev"

#  version:
#    needs: [path-files, terraform]
#    uses: ./.github/workflows/github_tag.yml

