github_main.ymlname: 'Terraform - Backed Dev'
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  path-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
             path1:
              - '.github/workflows/**'
             path2:
              - 'Path2/**'
  terraform:
    needs: path-files
    uses: ./.github/workflows/github_terraform.yml
    with:
      terraform_directory: "./Backend/dev"

  version:
    needs: [path-files, terraform]
    uses: ./.github/workflows/github-tag.yml

